### PR TITLE
Potential new site

### PR DESCRIPTION
**Pull request by Willian-Zhang**

### CODE REVIEW

**Comment by Willian-Zhang** [comment]
@Puriney please check

**Comment by Puriney** [comment]
If I clone the repository to my local computer, would the Large Files be also downloaded? If yes, I would say remove the data folder from code repository, otherwise keep. Repo is for reproducible codes. They can be fetched from public source. There is no meaning to keep them in repo.

**Comment by Puriney** [comment]
Submit the HTML to class as you like.

**Comment by Willian-Zhang** [comment]
yes they will, they will however download from different where than the git
repo

**Pull request closed without merging**
